version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
      exclude:
        - coverage-check
        - vouchington-tooling
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /dotnet-clients
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      xunit:
        applies-to: version-updates
        patterns:
          - xunit.analyzers
          - xunit.runner.visualstudio
          - xunit.v3
      xunit-security:
        applies-to: security-updates
        patterns:
          - xunit.analyzers
          - xunit.runner.visualstudio
          - xunit.v3

  - package-ecosystem: swift
    directory: /swift-clients/core
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      apple-swift-crypto:
        applies-to: version-updates
        patterns:
          - swift-crypto
          - swift-asn1
      apple-swift-crypto-security:
        applies-to: security-updates
        patterns:
          - swift-crypto
          - swift-asn1

  - package-ecosystem: swift
    directory: /swift-clients/ui
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      apple-swift-crypto:
        applies-to: version-updates
        patterns:
          - swift-crypto
          - swift-asn1
      apple-swift-crypto-security:
        applies-to: security-updates
        patterns:
          - swift-crypto
          - swift-asn1

  - package-ecosystem: swift
    directory: /swift-clients/apps/android
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      apple-swift-crypto:
        applies-to: version-updates
        patterns:
          - swift-crypto
          - swift-asn1
      apple-swift-crypto-security:
        applies-to: security-updates
        patterns:
          - swift-crypto
          - swift-asn1
      skip-toolchain:
        applies-to: version-updates
        patterns:
          - 'skip*'
      skip-toolchain-security:
        applies-to: security-updates
        patterns:
          - 'skip*'
