using System.Text.Json;
using Voucha.Client.Core.Api;

namespace Voucha.Client.Core.Tests.Api;

/// <summary>
/// Fixture-id -> response DTO type registry driving <see cref="ApiFixtureCoverageTests"/>'s
/// round-trip field-completeness gate (#6773). Every shared fixture this client consumes must
/// appear here or fail the coverage-gate test.
/// </summary>
internal static partial class ApiFixtureCoverage
{
  /// <summary>Fixture id -> response DTO type used to decode + re-encode it.</summary>
  public static readonly IReadOnlyDictionary<string, Type> Registry = new Dictionary<string, Type>(StringComparer.Ordinal)
  {
    ["shared.scopes.catalog"] = typeof(ScopeCatalogResponse),
    ["native.my.api-keys.create"] = typeof(ApiKeyCreationResponse),
    ["native.my.oauth-grants.paginated"] = typeof(OAuthGrantListResponse),
    ["native.users.followers.search"] = typeof(UserFollowersResponse),
    ["native.posts.followers.share"] = typeof(FollowerDistributionAcceptedResponse),
    ["native.posts.followers.send-selected"] = typeof(FollowerDistributionAcceptedResponse),
    ["native.rss-feed-items.followers.share"] = typeof(FollowerDistributionAcceptedResponse),
    ["native.rss-feed-items.followers.send-selected"] = typeof(FollowerDistributionAcceptedResponse),
    ["native.admin-ai-costs.default"] = typeof(AiCostTotalsResponse),
    ["native.identity-verification-attempts.grant.default"] = typeof(GrantIdentityVerificationAttemptResponse),
    ["native.admin-ai-costs.page-2"] = typeof(AiCostTotalsResponse),
    ["native.admin-ai-costs.empty"] = typeof(AiCostTotalsResponse),
    ["native.oauth.providers.broker-capabilities"] = typeof(OAuthProvidersResponse),
    ["native.oauth.authorization.begin"] = typeof(BeginOAuthAuthorizationResponse),
    ["native.oauth.authorization.complete.pending"] = typeof(OAuthCompletionResponse),
    ["native.oauth.authorization.complete.authenticated"] = typeof(OAuthCompletionResponse),
    ["native.oauth.authorization.complete.mfa"] = typeof(OAuthCompletionResponse),
    ["native.oauth.authorization.complete.connected"] = typeof(OAuthCompletionResponse),
    ["native.friend-recommendations.default"] = typeof(FriendRecommendationsResponse),
    ["native.friend-recommendations.second-page"] = typeof(FriendRecommendationsResponse),
    ["native.friend-recommendations.empty"] = typeof(FriendRecommendationsResponse),
    ["native.import-export.rss-feeds.submit.default"] = typeof(RssFeedImportSubmission),
    ["native.import-export.rss-feeds.status.retrying"] = typeof(RssFeedImportStatus),
    ["native.import-export.rss-feeds.status.partial"] = typeof(RssFeedImportStatus),
    ["native.import-export.topics.import.outcomes"] = typeof(TopicImportResponse),
    ["native.import-export.topics.export.default"] = typeof(TopicExportResponse),
    ["native.import-export.topics.export.download"] = typeof(IReadOnlyList<ExportTopic>),
    ["native.feature-flags.default"] = typeof(FeatureFlagsResponse),
    ["native.captcha-config.default"] = typeof(CaptchaConfigResponse),
    ["native.topic-recommendations.top-hashtags.default"] = typeof(TopHashtagsResponse),
    ["native.dynamic-config.namespaces.developer"] = typeof(DynamicConfigNamespacesResponse),
    ["native.dynamic-config.namespace.typed"] = typeof(DynamicConfigNamespaceResponse),
    ["native.dynamic-config.namespace.string"] = typeof(DynamicConfigNamespaceResponse),
    ["native.dynamic-config.namespace.integer"] = typeof(DynamicConfigNamespaceResponse),
    ["native.dynamic-config.update.changed"] = typeof(DynamicConfigUpdateResponse),
    ["native.dynamic-config.update.no-op"] = typeof(DynamicConfigUpdateResponse),
    ["native.dynamic-config.history.default"] = typeof(DynamicConfigHistoryResponse),
    ["web.communities.members.default"] = typeof(CommunityMembersResponse),
    ["web.communities.archive.default"] = typeof(CommunityResponse),
    ["web.communities.posts.default"] = typeof(CommunityPostsResponse),
    ["web.communities.list-items.rss-feeds.default"] = typeof(CommunityListRssFeedsResponse),
    ["web.communities.list-items.posts.default"] = typeof(CommunityListPostsResponse),
    ["web.communities.list-items.domains.default"] = typeof(CommunityListDomainsResponse),
    ["web.communities.list-items.urls.default"] = typeof(CommunityListUrlsResponse),
    ["web.communities.list-items.counts.default"] = typeof(CommunityListItemCountsResponse),
    ["web.communities.list-items.topics.default"] = typeof(CommunityListTopicsResponse),
    ["web.communities.application-questions.default"] = typeof(CommunityApplicationQuestionsResponse),
    ["web.communities.pinned-posts.default"] = typeof(CommunityPinnedPostsResponse),
    ["web.communities.moderation-queue.default"] = typeof(CommunityModerationQueueResponse),
    ["native.community.pending-reports.paginated"] = typeof(CommunityPendingReportsResponse),
    ["web.communities.moderation-analytics.default"] = typeof(CommunityModerationAnalyticsResponse),
    ["web.communities.modmail-messages.default"] = typeof(CommunityModmailMessageListResponse),
    ["web.communities.modlog.default"] = typeof(ModlogResponse),
    ["web.communities.moderator-stats.default"] = typeof(CommunityModeratorStatsResponse),
    ["web.communities.moderator-vacation.default"] = typeof(ModeratorVacationResponse),
    ["native.moderation.reports.default"] = typeof(StaffFlatModerationReportsResponse),
    ["native.moderation.reports.member.default"] = typeof(MemberFlatModerationReportsResponse),
    ["native.moderation.reports.clustered.default"] = typeof(StaffClusteredModerationReportsResponse),
    ["native.moderation.reports.clustered.page-2"] = typeof(StaffClusteredModerationReportsResponse),
    ["native.moderation.report-judgement.default"] = typeof(ModerationReportJudgementResponse),
    ["native.moderation.report-resolution.reviewed"] = typeof(ModerationReportResolutionResponse),
    ["native.moderation.admin-warning.report"] = typeof(AdminUserWarningResponse),
    ["native.moderation.appeals.default"] = typeof(ModerationAppealListResponse),
    ["native.moderation.appeals.page-2"] = typeof(ModerationAppealListResponse),
    ["native.moderation.appeals.update.default"] = typeof(ModerationAppealResponse),
    ["native.moderation.appeals.approval.default"] = typeof(ModerationAppealResponse),
    ["native.moderation.appeals.delivery.default"] = typeof(ModerationAppealResponse),
    ["native.moderation.appeals.resolution.accept"] = typeof(ModerationAppealResponse),
    ["native.moderation.appeals.resolution.reduce"] = typeof(ModerationAppealResponse),
    ["native.moderation.appeals.resolution.deny"] = typeof(ModerationAppealResponse),
    ["native.moderation.appeals.resolution-drafts.default"] = typeof(ModerationAppealQueueResponse),
    ["native.moderation.disputes.default"] = typeof(ModerationDisputeListResponse),
    ["native.moderation.disputes.detail.default"] = typeof(ModerationDisputeResponse),
    ["native.moderation.disputes.update.default"] = typeof(ModerationDisputeResponse),
    ["native.moderation.disputes.approval.default"] = typeof(ModerationDisputeResponse),
    ["native.moderation.disputes.delivery.default"] = typeof(ModerationDisputeResponse),
    ["native.moderation.disputes.resolution.remove"] = typeof(ModerationDisputeResponse),
    ["native.moderation.disputes.resolution.annotate"] = typeof(ModerationDisputeResponse),
    ["native.moderation.disputes.resolution.dismiss"] = typeof(ModerationDisputeResponse),
    ["native.moderation.disputes.resolution-drafts.default"] = typeof(ModerationDisputeQueueResponse),
    ["native.moderation.review-queue.default"] = typeof(AdminReviewQueueResponse),
    ["native.moderation.review-queue.page-2"] = typeof(AdminReviewQueueResponse),
    ["native.moderation.exposure.default"] = typeof(ModerationExposureResponse),
    ["native.moderation.reveals.default"] = typeof(ModerationExposureResponse),
    ["native.moderation.removed-posts.default"] = typeof(PersonalRemovedPostsResponse),
    ["native.moderation.removed-posts.page-2"] = typeof(PersonalRemovedPostsResponse),
    ["native.moderation.clearance.approved"] = typeof(ClearanceUpdateResponse),
    ["native.moderation.clearance.rejected"] = typeof(ClearanceUpdateResponse),
    ["native.moderation.clearance.in-review"] = typeof(ClearanceUpdateResponse),
    ["native.moderation.modlog.default"] = typeof(ModlogResponse),
    ["native.moderation.analytics.default"] = typeof(CommunityModerationAnalyticsResponse),
    ["native.moderation.transparency.default"] = typeof(ModerationTransparencyResponse),
    ["native.community.moderation-transparency.default"] = typeof(ModerationTransparencyResponse),
    ["native.moderation.vote-integrity.default"] = typeof(VoteIntegrityFlagsResponse),
    ["native.moderation.vote-integrity.pending"] = typeof(VoteIntegrityFlagsResponse),
    ["native.moderation.vote-integrity.resolved"] = typeof(VoteIntegrityFlagsResponse),
    ["native.moderation.vote-integrity.resolution.dismissed"] = typeof(VoteIntegrityFlagResponse),
    ["native.moderation.vote-integrity.resolution.penalized"] = typeof(VoteIntegrityFlagResponse),
    ["native.moderation.vote-integrity.resolution.suspended"] = typeof(VoteIntegrityFlagResponse),
    ["native.moderation.vote-integrity.penalty"] = typeof(VoteIntegrityPenaltyApplicationResponse),
    ["native.moderation.vote-integrity.penalties.default"] = typeof(VoteIntegrityPenaltiesResponse),
    ["native.moderation.vote-integrity.penalties.active"] = typeof(VoteIntegrityPenaltiesResponse),
    ["native.moderation.vote-integrity.penalties.revoked"] = typeof(VoteIntegrityPenaltiesResponse),
    ["native.moderation.vote-integrity.penalties.all"] = typeof(VoteIntegrityPenaltiesResponse),
    ["native.moderation.vote-integrity.penalties.page-2"] = typeof(VoteIntegrityPenaltiesResponse),
    ["native.moderation.vote-integrity.penalties.get"] = typeof(VoteWeightPenaltyResponse),
    ["native.moderation.vote-integrity.penalties.revoke"] = typeof(VoteWeightPenaltyResponse),
    ["native.moderation.report-integrity.default"] = typeof(ReportIntegrityFlagsResponse),
    ["native.moderation.report-integrity.pending"] = typeof(ReportIntegrityFlagsResponse),
    ["native.moderation.report-integrity.resolved"] = typeof(ReportIntegrityFlagsResponse),
    ["native.moderation.report-integrity.resolution.dismissed"] = typeof(ReportIntegrityFlagResponse),
    ["native.moderation.report-integrity.penalty"] = typeof(ReportIntegrityPenaltyResponse),
    ["native.moderation.report-integrity.penalties.default"] = typeof(ReportIntegrityPenaltiesResponse),
    ["native.moderation.report-integrity.penalties.active"] = typeof(ReportIntegrityPenaltiesResponse),
    ["native.moderation.report-integrity.penalties.revoked"] = typeof(ReportIntegrityPenaltiesResponse),
    ["native.moderation.report-integrity.penalties.all"] = typeof(ReportIntegrityPenaltiesResponse),
    ["native.moderation.report-integrity.penalties.page-2"] = typeof(ReportIntegrityPenaltiesResponse),
    ["native.moderation.report-integrity.penalties.get"] = typeof(ReportAbusePenaltyResponse),
    ["native.moderation.report-integrity.penalties.revoke"] = typeof(ReportAbusePenaltyResponse),
    ["web.communities.ai-agents.default"] = typeof(CommunityAiAgentsResponse),
    ["web.communities.agent-prompts.default"] = typeof(CommunityAgentPromptsResponse),
    ["web.communities.agent-prompts.history.default"] = typeof(CommunityAgentPromptHistoryResponse),
    ["web.communities.automod-simulate.default"] = typeof(CommunityAutomodSimulation),
    ["web.communities.search.default"] = typeof(CommunitySearchResponse),
    ["web.communities.show.default"] = typeof(CommunityResponse),
    ["web.communities.ai-agent.default"] = typeof(UpsertCommunityAiAgentResponse),
    ["web.communities.news.default"] = typeof(RssFeedItemsFeedResponse),
    ["web.communities.applications.default"] = typeof(CommunityApplicationsResponse),
    ["web.communities.invites.default"] = typeof(CommunityInvitesResponse),
    ["web.communities.bans.default"] = typeof(CommunityBansResponse),
    ["web.communities.restrictions.default"] = typeof(CommunityRestrictionsResponse),
    ["web.communities.modmail.default"] = typeof(CommunityModmailThreadListResponse),
    ["web.communities.modmail.page-2"] = typeof(CommunityModmailThreadListResponse),
    ["web.communities.modmail-messages.page-2"] = typeof(CommunityModmailMessageListResponse),
    ["web.communities.saved-replies.default"] = typeof(CommunitySavedRepliesResponse),
    ["web.communities.saved-replies.page-2"] = typeof(CommunitySavedRepliesResponse),
    ["web.communities.saved-reply.create.default"] = typeof(CommunitySavedReplyResponse),
    ["web.communities.automod-recent-actions.default"] = typeof(CommunityAutomodActionsResponse),
    ["web.communities.automod-feedback.create.default"] = typeof(CommunityAutomodFeedbackResponse),
    ["web.communities.moderation-results.default"] = typeof(CommunityModerationResultsResponse),
    ["web.communities.warning.create.default"] = typeof(CommunityWarningResponse),
    ["web.communities.post-type-settings.update.default"] = typeof(CommunityMutationResponse),
    ["web.growth-metrics.default"] = typeof(GrowthMetricsResponse),
    ["shared.currencies.list.default"] = typeof(CurrenciesResponse),
    ["web.topics.search.default"] = typeof(TopicSearchResponse),
    ["web.topics.mutation.default"] = typeof(TopicMutationResponse),
    ["web.topics.publisher-types.default"] = typeof(PublisherTypeTopicsResponse),
    ["native.topics.user-tags.default"] = typeof(UserTagTopicsResponse),
    ["web.topics.search.referral-programs.default"] = typeof(TopicSearchResponse),
    ["web.rss-feed-items.feed.default"] = typeof(RssFeedItemsFeedResponse),
    ["native.rss-feed-item.detail.default"] = typeof(RssFeedItemResponse),
    ["native.topic-recommendation.detail.default"] = typeof(PostResponse),
    ["web.referral-links.feed.default"] = typeof(ReferralLinkFeedResponse),
    ["web.referral-links.prioritized.default"] = typeof(PrioritizedReferralLinksResponse),
    ["web.trending-referral-programs.default"] = typeof(TrendingReferralProgramsResponse),
    ["swift.posts.feed.default"] = typeof(PostsFeedResponse),
    ["swift.notifications.default"] = typeof(NotificationsResponse),
    ["native.notifications.redirect-target.default"] = typeof(NotificationRedirectTargetResponse),
    ["swift.users.following.default"] = typeof(UserFollowingResponse),
    ["swift.users.followers.default"] = typeof(UserFollowersResponse),
    ["swift.my.identity.default"] = typeof(MyIdentityResponse),
    ["native.my.email-preferences.default"] = typeof(EmailPreferencesResponse),
    ["native.my.email-addresses.empty"] = typeof(EmailAddressListResponse),
    ["native.my.api-keys.paginated"] = typeof(ApiKeyListResponse),
    ["native.my.push-subscriptions.paginated"] = typeof(WebPushSubscriptionListResponse),
    ["native.my.email-addresses.request.default"] = typeof(EmailAddressRequestResponse),
    ["native.my.email-addresses.verify.default"] = typeof(EmailAddressListResponse),
    ["native.users.delete.default"] = typeof(DeleteUserResponse),
    ["native.users.data-request.default"] = typeof(UserDataRequestResponse),
    ["native.users.data-request.create.default"] = typeof(UserDataRequestCreationResponse),
    ["native.auth.sessions.default"] = typeof(AuthSessionListResponse),
    ["native.auth.bluesky.link.default"] = typeof(BeginBlueskyAccountLinkResponse),
    ["native.auth.bluesky.link.native"] = typeof(BeginBlueskyAccountLinkResponse),
    ["native.fediverse.instances.default"] = typeof(FediverseInstancesResponse),
    ["native.fediverse.instances.page-2"] = typeof(FediverseInstancesResponse),
    ["native.fediverse.instances.empty"] = typeof(FediverseInstancesResponse),
    ["native.fediverse.instance.slug"] = typeof(FediverseInstanceResponse),
    ["native.fediverse.instance.uuid"] = typeof(FediverseInstanceResponse),
    ["swift.my.profile.default"] = typeof(MyProfileResponse),
    ["swift.rss-feeds.default"] = typeof(RssFeedsResponse),
    ["swift.rss-feed-items.feed.default"] = typeof(RssFeedItemsFeedResponse),
    ["swift.integration.rss-feed-items.video"] = typeof(RssFeedItemsFeedResponse),
    ["swift.integration.rss-feed-items.audio"] = typeof(RssFeedItemsFeedResponse),
    ["swift.podcast-episode-chapters.default"] = typeof(PodcastEpisodeChaptersResponse),
    ["swift.podcast-playback-position.default"] = typeof(PodcastPlaybackPositionResponse),
    ["native.users.profile.default"] = typeof(UserResponse),
    ["native.users.profile.restricted"] = typeof(UserResponse),
    ["native.users.vouch-context.default"] = typeof(UserTrustContext),
    ["native.users.profile.topics-following.first-page"] = typeof(BookmarkCollectionResponse<Topic>),
    ["native.users.profile.topics-following.next-page"] = typeof(BookmarkCollectionResponse<Topic>),
    ["native.users.profile.sources-following.article"] = typeof(RssFeedsResponse),
    ["native.users.profile.communities-member.first-page"] = typeof(BookmarkCollectionResponse<Community>),
    ["native.users.profile.communities-member.next-page"] = typeof(BookmarkCollectionResponse<Community>),
    ["native.messages.conversations.default"] = typeof(DirectConversationsResponse),
    ["native.messages.conversations.page-2"] = typeof(DirectConversationsResponse),
    ["native.messages.conversation.default"] = typeof(DirectConversationResponse),
    ["native.messages.create.default"] = typeof(DirectConversationResponse),
    ["native.messages.thread.default"] = typeof(DirectMessagesResponse),
    ["native.messages.thread.page-2"] = typeof(DirectMessagesResponse),
    ["native.messages.send.default"] = typeof(DirectMessageResponse),
    ["native.messages.participants.default"] = typeof(DirectMessageParticipantsResponse),
    ["native.messages.participant-add.default"] = typeof(DirectMessageParticipantResponse),
    ["native.messages.policy.default"] = typeof(DirectConversationPolicyResponse),
    ["native.messages.user-search.default"] = typeof(UsersSearchResponse),
    ["native.memberships.plans.default"] = typeof(MembershipPlansResponse),
    ["native.memberships.me.default"] = typeof(JsonElement),
    ["native.memberships.grant.default"] = typeof(GrantMembershipResponse),
    ["native.comments.post-detail.default"] = typeof(PostResponse),
    ["native.comments.descendants.default"] = typeof(PostThreadResponse),
    ["native.comments.ancestors.permalink"] = typeof(PostThreadResponse),
    ["native.comments.ancestors.bounded.shallow"] = typeof(PostThreadResponse),
    ["native.comments.ancestors.bounded.deep-initial"] = typeof(PostThreadResponse),
    ["native.comments.ancestors.bounded.deep-continuation"] = typeof(PostThreadResponse),
    ["native.lists.default"] = typeof(ListsSearchResponse),
    ["native.list-items.default"] = typeof(ListItemsResponse),
    ["native.lists-containing.default"] = typeof(ListsContainingResponse),
    ["native.list-import.default"] = typeof(ImportCommunityListResponse),
    ["native.landing-pages.default"] = typeof(LandingPagesResponse),
    ["native.landing-page-detail.default"] = typeof(LandingPageDetailResponse),
    ["native.landing-page-analytics.default"] = typeof(LandingPageAnalyticsResponse),
    ["native.admin-user-landing-pages.default"] = typeof(LandingPagesResponse),
    ["native.admin-landing-page-analytics.default"] = typeof(AdminLandingPageAnalyticsResponse),
    ["native.landing-page-candidates.default"] = typeof(LandingPageCandidatesResponse),
    ["native.landing-page-items-mutation.default"] = typeof(LandingPageDetailResponse),
    ["native.landing-page-mutation.default"] = typeof(LandingPageResponse),
    ["native.households.empty"] = typeof(HouseholdsResponse),
    ["native.households.single-owned"] = typeof(HouseholdsResponse),
    ["native.households.multiple"] = typeof(HouseholdsResponse),
    ["native.households.owned"] = typeof(HouseholdsResponse),
    ["native.households.member.default"] = typeof(HouseholdsResponse),
    ["native.households.member.page-2"] = typeof(HouseholdsResponse),
    ["native.household-memberships.empty"] = typeof(HouseholdMembershipsResponse),
    ["native.household-memberships.single"] = typeof(HouseholdMembershipsResponse),
    ["native.household-memberships.multiple"] = typeof(HouseholdMembershipsResponse),
    ["native.household-memberships.page-1"] = typeof(HouseholdMembershipsResponse),
    ["native.household-memberships.page-2"] = typeof(HouseholdMembershipsResponse),
    ["native.households.create.default"] = typeof(HouseholdCreateResponse),
    ["native.card-topics.search.default"] = typeof(TopicSearchResponse),
    ["native.cards.empty"] = typeof(PaymentCardsResponse),
    ["native.cards.page-1"] = typeof(PaymentCardsResponse),
    ["native.cards.page-2"] = typeof(PaymentCardsResponse),
    ["native.cards.create.default"] = typeof(PaymentCardResponse),
    ["native.cards.update.full"] = typeof(PaymentCardResponse),
    ["native.cards.update.clear"] = typeof(PaymentCardResponse),
    ["native.rewards-program-topics.search.default"] = typeof(TopicSearchResponse),
    ["native.rewards-program-status-topics.search.default"] = typeof(TopicSearchResponse),
    ["native.point-valuations.empty"] = typeof(PointValuationsResponse),
    ["native.point-valuations.page-1"] = typeof(PointValuationsResponse),
    ["native.point-valuations.page-2"] = typeof(PointValuationsResponse),
    ["native.point-valuations.create.default"] = typeof(PointValuationResponse),
    ["native.point-valuations.update.full"] = typeof(PointValuationResponse),
    ["native.point-valuations.update.clear-note"] = typeof(PointValuationResponse),
    ["native.spending-categories.empty"] = typeof(SpendingCategoriesResponse),
    ["native.spending-categories.page-1"] = typeof(SpendingCategoriesResponse),
    ["native.spending-categories.owned-household"] = typeof(SpendingCategoriesResponse),
    ["native.spending-categories.page-2"] = typeof(SpendingCategoriesResponse),
    ["native.spending-categories.create.default"] = typeof(SpendingCategoryResponse),
    ["native.spending-categories.update.clear-note"] = typeof(SpendingCategoryResponse),
    ["native.spending-category-topics.search.default"] = typeof(TopicSearchResponse),
    ["native.rewards-statuses.empty"] = typeof(RewardsProgramStatusesResponse),
    ["native.rewards-statuses.page-1"] = typeof(RewardsProgramStatusesResponse),
    ["native.rewards-statuses.page-2"] = typeof(RewardsProgramStatusesResponse),
    ["native.rewards-statuses.create.default"] = typeof(RewardsProgramStatusResponse),
    ["native.rewards-statuses.update.full"] = typeof(RewardsProgramStatusResponse),
    ["native.rewards-statuses.update.clear-dates"] = typeof(RewardsProgramStatusResponse),
    ["native.entity-relations.post.category.topic.default"] = typeof(EntityRelationsResponse),
    ["native.entity-relations.post.related.post.default"] = typeof(EntityRelationsResponse),
    ["native.entity-relations.post.related.url.default"] = typeof(EntityRelationsResponse),
    ["native.entity-relations.topic.publisher-type.topic.default"] = typeof(EntityRelationsResponse),
    ["native.entity-relations.rss-feed-item.category.topic.default"] = typeof(EntityRelationsResponse),
    ["native.entity-relations.post.category.topic.create.default"] = typeof(EntityRelationResponse),
    ["native.entity-relations.user.category.topic.default"] = typeof(EntityRelationsResponse),
    ["native.entity-relations.user.category.topic.create.default"] = typeof(EntityRelationResponse),
    ["native.bookmarks.posts.saved.default"] = typeof(BookmarkCollectionResponse<Post>),
    ["native.bookmarks.posts.saved.next-page"] = typeof(BookmarkCollectionResponse<Post>),
    ["native.bookmarks.topics.muted.default"] = typeof(BookmarkCollectionResponse<Topic>),
    ["native.bookmarks.topics.viewed.default"] = typeof(BookmarkCollectionResponse<Topic>),
    ["native.bookmarks.users.subscribed-posts.default"] = typeof(BookmarkCollectionResponse<User>),
    ["native.bookmarks.users.dismissed-recommendations.default"] = typeof(BookmarkCollectionResponse<User>),
    ["native.bookmarks.rss-feed-items.saved.default"] = typeof(BookmarkCollectionResponse<RssFeedItem>),
    ["native.bookmarks.rss-feeds.muted.default"] = typeof(BookmarkCollectionResponse<RssFeedSource>),
    ["native.bookmarks.rss-feeds.viewed.default"] = typeof(BookmarkCollectionResponse<RssFeedSource>),
    ["native.bookmarks.urls.saved.default"] = typeof(BookmarkCollectionResponse<Url>),
    ["native.bookmarks.domains.blocked.default"] = typeof(BookmarkCollectionResponse<Hostname>),
    ["native.bookmarks.domains.muted.default"] = typeof(BookmarkCollectionResponse<Hostname>),
    ["native.bookmarks.communities.proxy-following.default"] = typeof(BookmarkCollectionResponse<Community>),
    ["native.referral-links.mine.default"] = typeof(ReferralLinksResponse),
    ["native.referral-clicks.mine.default"] = typeof(ReferralClickLogResponse),
    ["native.hostnames.default"] = typeof(HostnamesResponse),
    ["native.hostname.default"] = typeof(HostnameDetailResponse),
    ["native.urls.default"] = typeof(UrlSearchResponse),
    ["native.url.default"] = typeof(UrlDetailResponse),
    ["native.url-crawls.default"] = typeof(UrlCrawlsResponse),
    ["native.paid.url-crawls.default"] = typeof(UrlCrawlsResponse),
    ["native.url-crawl.default"] = typeof(UrlCrawlResponse),
    ["native.paid.url-crawl.default"] = typeof(UrlCrawlResponse),
    ["web.paid.rss-feed-crawls.default"] = typeof(RssFeedCrawlsResponse),
    ["web.paid.rss-feed-crawl.default"] = typeof(RssFeedCrawlResponse),
    ["web.admin.rss-feed-crawl.default"] = typeof(RssFeedCrawlResponse),
    ["native.url-crawl-trigger.default"] = typeof(UrlCrawlTriggerResponse),
    ["web.admin.article-syncs.trigger.default"] = typeof(ArticleSyncTriggerResponse),
    ["web.admin.article-syncs.status.active"] = typeof(ArticleSyncJobStatusResponse),
    ["web.admin.mq.stats.default"] = typeof(QueueStatsSummaryResponse),
    ["web.admin.mq.queues.default"] = typeof(QueueStatsResponse),
    ["web.admin.mq.queues.pause.default"] = typeof(EngineeringSuccessResponse),
    ["web.admin.mq.queues.resume.default"] = typeof(EngineeringSuccessResponse),
    ["web.admin.mq.scheduled-jobs.default"] = typeof(ScheduledJobsResponse),
    ["web.admin.mq.scheduled-jobs.trigger.default"] = typeof(EngineeringSuccessResponse),
    ["web.admin.mq.backfills.default"] = typeof(BackfillsResponse),
    ["web.admin.mq.backfills.trigger.default"] = typeof(EngineeringSuccessResponse),
    ["web.admin.psql.migrations.default"] = typeof(PsqlMigrationsResponse),
    ["web.admin.psql.partitions.default"] = typeof(PartitionStatusResponse),
    ["web.admin.psql.jobs.default"] = typeof(EngineeringSuccessResponse),
    ["web.admin.valkey.bloom-filters.rebuild.default"] = typeof(RebuildBloomFilterResponse),
    ["web.admin.valkey.cache-groups.default"] = typeof(CacheGroupsResponse),
    ["web.admin.valkey.caches.clear.default"] = typeof(ClearCacheResponse),
    ["web.admin.valkey.flush.default"] = typeof(FlushValkeyResponse),
  };

  /// <summary>
  /// Per-fixture key paths this client intentionally does not model, with a one-line reason.
  /// A path here must be a real gap between the fixture and the DTO.
  /// </summary>
  public static readonly IReadOnlyDictionary<string, string[]> IgnoredPaths =
      new Dictionary<string, string[]>(StringComparer.Ordinal)
      {
        ["native.topic-recommendation.detail.default"] =
        [
          "post.topic_recommendation",
          "post.topic_recommendation.aliases",
          "post.topic_recommendation.approval_error_message",
          "post.topic_recommendation.created_topic_id",
          "post.topic_recommendation.created_topic_slug",
          "post.topic_recommendation.example_referral_link",
          "post.topic_recommendation.hostname",
          "post.topic_recommendation.hostname_id",
          "post.topic_recommendation.hostnames",
          "post.topic_recommendation.landing_page_urls",
          "post.topic_recommendation.post_id",
          "post.topic_recommendation.rejection_reason",
          "post.topic_recommendation.reviewed_at",
          "post.topic_recommendation.reviewed_by_id",
          "post.topic_recommendation.status",
          "post.topic_recommendation.topic_markdown",
          "post.topic_recommendation.topic_slug",
          "post.topic_recommendation.topic_title",
          "post.topic_recommendation.topic_type",
          "post.topic_recommendation.topic_wikipedia_pageid",
        ],
      };
}
