namespace Voucha.Client.Core.Tests.Api;

internal static class IntegrityPenaltyFixtureConstants
{
  public const string ReportPageOneEndCursor =
      "eyJpZCI6IjAxOWY3MDAwLTAwMDAtNzAwMC04MDAwLTAwMDAwMDAwMDEwMiIsInNjb3BlIjoie1wicmVzb3VyY2VcIjpcInJlcG9ydC1hYnVzZS1wZW5hbHRpZXNcIixcInN0YXR1c1wiOlwiYWN0aXZlXCIsXCJ1c2VyX2lkXCI6bnVsbCxcInNvdXJjZV9mbGFnX2lkXCI6bnVsbCxcIm9yZGVyXCI6XCJpZC1kZXNjXCJ9In0";

  public const string VotePageOneEndCursor =
      "eyJpZCI6IjAxOWY3MDAwLTAwMDAtNzAwMC04MDAwLTAwMDAwMDAwMDIwMyIsInNjb3BlIjoie1wicmVzb3VyY2VcIjpcInZvdGUtd2VpZ2h0LXBlbmFsdGllc1wiLFwic3RhdHVzXCI6XCJhY3RpdmVcIixcInNvdXJjZVwiOlwiZmxhZ1wiLFwidXNlcl9pZFwiOm51bGwsXCJzb3VyY2VfZmxhZ19pZFwiOm51bGwsXCJvcmRlclwiOlwiaWQtZGVzY1wifSJ9";
}
