public extension PrivateUser {
    func withProfileImageId(_ profileImageId: String?) -> PrivateUser {
        PrivateUser(
            entityType: entityType,
            id: id,
            username: username,
            useDisplayNameFrom: useDisplayNameFrom,
            roles: roles,
            accountType: accountType,
            profileImageId: profileImageId,
            markdown: markdown,
            emailAddress: emailAddress,
            membershipPlan: membershipPlan,
            verificationStatus: verificationStatus,
            suspendedAt: suspendedAt,
            cardsVisibility: cardsVisibility,
            rewardsProgramStatusesVisibility: rewardsProgramStatusesVisibility,
            spendingCategoriesVisibility: spendingCategoriesVisibility,
            followsVisibility: followsVisibility,
            topicFollowsVisibility: topicFollowsVisibility,
            rssFeedFollowsVisibility: rssFeedFollowsVisibility,
            communityMembershipsVisibility: communityMembershipsVisibility,
            followersVisibility: followersVisibility,
            likesVisibility: likesVisibility,
            directMessagesAudience: directMessagesAudience,
            defaultPostBroadcast: defaultPostBroadcast,
            defaultPostPrivacy: defaultPostPrivacy,
            engagementEmailsEnabled: engagementEmailsEnabled,
            newsDigestFrequency: newsDigestFrequency,
            moderationEmailsEnabled: moderationEmailsEnabled,
            communityDigestFrequency: communityDigestFrequency,
            moderationEmailCadence: moderationEmailCadence,
            moderationEmailDaysOfWeek: moderationEmailDaysOfWeek,
            moderationEmailTimeOfDay: moderationEmailTimeOfDay,
            moderationEmailTimezone: moderationEmailTimezone,
            fediverseFederationEnabled: fediverseFederationEnabled,
            blueskyAccount: blueskyAccount,
            facebookAccount: facebookAccount,
            xAccount: xAccount,
            githubAccount: githubAccount,
            processingRestrictedAt: processingRestrictedAt,
            thirdPartyMarketing: thirdPartyMarketing,
            hnDiscussions: hnDiscussions,
            country: country,
            uiLocale: uiLocale
        )
    }
}
