namespace Voucha.Client.Core.Navigation;

public static partial class NativeRouteCatalog
{
  private static NativeRouteCatalogEntry[] EntityEntries() =>
  [
    Included("Source detail", NativeRouteDestinationId.SourceDetail, "/source/example", SourceDetailPatterns()),
    Included("Topic detail", NativeRouteDestinationId.TopicDetail, "/topic/hello-world", TopicDetailPatterns()),
    Included("Topic management", NativeRouteDestinationId.TopicManagement, "/topics/create",
        TopicManagementPatterns()),
    Included(
        "Import and export",
        NativeRouteDestinationId.ImportExport,
        "/my/topics/import-export",
        [
          "/my/topics/import-export", "/my/sources/import-export", "/my/news-sources/import-export",
          "/my/podcasts/import-export", "/my/channels/import-export",
        ]),
    Included("Tag management", NativeRouteDestinationId.TagManagement, "/review/123/tags/topic", TagManagementPatterns()),
    Included(
        "Sources browse",
        NativeRouteDestinationId.SourcesBrowse,
        "/sources",
        ["/sources"]),
    Included("News sources browse", NativeRouteDestinationId.FeedNews, "/news-sources",
        ["/news-sources", "/my/news-sources"]),
    Included("Podcast sources browse", NativeRouteDestinationId.FeedPodcasts, "/podcasts",
        ["/podcasts", "/podcasts/:category", "/my/podcasts"]),
    Included("Video channels browse", NativeRouteDestinationId.FeedVideos, "/channels",
        ["/channels", "/my/channels"]),
    Included("Fediverse search", NativeRouteDestinationId.FediverseSearch, "/fediverse", ["/fediverse"]),
    Included("Fediverse instances", NativeRouteDestinationId.FediverseInstances, "/instances", ["/instances"]),
    Included("Domains browse", NativeRouteDestinationId.DomainsBrowse, "/domains", ["/domains"]),
    Included("Domain detail", NativeRouteDestinationId.DomainDetail, "/domain/example.com", ["/domain/:idOrHostname"]),
    Included("URLs browse", NativeRouteDestinationId.UrlsBrowse, "/urls", ["/urls"]),
    Included("Domain compare", NativeRouteDestinationId.DomainsBrowse, "/domains/compare", ["/domains/compare"]),
    Included("URL detail", NativeRouteDestinationId.UrlDetail, "/url/url-1",
        ["/url/:id", "/url/:id/crawls", "/url/:id/crawls/:crawlId", "/crawler/:id", "/crawler/:id/edit"]),
    Included("Users browse", NativeRouteDestinationId.UsersBrowse, "/users",
        ["/users", "/my/friend-recommendations", "/my/users/dismissed-recommendations"]),
    Included("User profile", NativeRouteDestinationId.UserProfile, "/user/alice", UserProfilePatterns()),
    Included("Community action forms", NativeRouteDestinationId.CommunityAction, "/communities/create",
        ["/communities/create", "/communities/invite/:code", "/communities/:slug/apply"]),
    Included("Communities browse", NativeRouteDestinationId.CommunitiesBrowse, "/communities", ["/communities", "/communities/lists"]),
    Included(
        "Community detail",
        NativeRouteDestinationId.CommunityDetail,
        "/communities/voucha",
        [
          "/communities/:slug",
          "/communities/:slug/about",
          "/communities/:slug/lists",
          "/communities/:slug/lists/:itemType",
          "/communities/:slug/members",
          "/communities/:slug/news",
          "/communities/:slug/news/sources",
          "/communities/:slug/news/topics",
          "/communities/:slug/posts",
          "/communities/:slug/posts/pending",
          "/communities/:slug/pinned-posts",
          "/communities/:slug/applications",
          "/communities/:slug/invites",
          "/communities/:slug/bans",
          "/communities/:slug/restrictions",
          "/communities/:slug/modlog",
          "/communities/:slug/modmail",
          "/communities/:slug/modmail/:threadId",
          "/communities/:slug/moderator-stats",
          "/communities/:slug/moderator-vacation",
          "/communities/:slug/moderation-queue",
          "/communities/:slug/moderation-analytics",
          "/communities/:slug/ai-agents",
          "/communities/:slug/agent-prompts",
          "/communities/:slug/automod/recent-actions",
          "/communities/:slug/automod/simulate",
          "/communities/:slug/settings/**",
        ]),
    Included("Messages", NativeRouteDestinationId.Messages, "/messages/123",
        ["/messages", "/messages/new", "/messages/:conversationId", "/messages/modmail/:communitySlug/:threadId"]),
    Included("Support", NativeRouteDestinationId.Support, "/chat/support", ["/chat/support", "/chat/support/new", "/chat/support/:threadId"]),
    Included("Chat", NativeRouteDestinationId.Chat, "/chat", ["/chat", "/chat/:id"]),
    Included("Notifications", NativeRouteDestinationId.Notifications, "/my/notifications", ["/my/notifications", "/notification-redirect"]),
  ];
}
